---
- name: Fail if OS is not supported
  ansible.builtin.fail:
    msg: "The Site24x7 Ansible role does not support your OS yet. Please email support@site24x7.com to open a feature request."
  when: ansible_facts.os_family not in ["RedHat", "Rocky", "AlmaLinux", "Debian", "Suse", "Darwin"]
